# Generated by Django 5.0.1 on 2024-01-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
